### ISSUE TITLE
MBE Practical Example: Table width causes wrap in first column

### ISSUE THREAD

**Issue by archaephyrryx** [Veykril/tlborm#67]
The rendered version of the book has a CSS rule defined in [`variables.css`](https://veykril.github.io/tlborm/css/variables.css) as follows

```css
:root {
    --sidebar-width: 300px;
    --page-padding: 15px;
    --content-max-width: 750px;
    --menu-bar-height: 50px;
}
```

This definition of a max width of 750px causes the parse-table element on the practical introduction section of the MBE chapter to line-wrap in the first column, which makes the block-arrow indicator very difficult to follow.

I found that relaxing this constraint to even `900px` in my browser inspector caused the table to widen enough that the wrapping no longer occurred, at least on my display and browser:

![At default 750px](https://user-images.githubusercontent.com/1379729/163858167-ed1834a1-a20e-4c75-9b43-232aa31d6053.png)

![After widening to 900px](https://user-images.githubusercontent.com/1379729/163858176-f8543c36-0577-4561-bdec-06ed5c140d86.png)
